name: web_video_pick_show
description: "Package to pick and show video in web. To pick it uses image_picker_web under the hook."

repository: https://github.com/AradhyaNepal/web_video_pick_show
issue_tracker: https://github.com/AradhyaNepal/web_video_pick_show/issues


version: 0.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  image_picker_web: ^4.0.0
  flutter:
    sdk: flutter



